public enum CommandType {
    COMMAND_BYE,
    COMMAND_LIST,
    COMMAND_TODO,
    COMMAND_DONE,
    COMMAND_DEADLINE,
    COMMAND_EVENT,
    COMMAND_DELETE,
    COMMAND_FIND,
    COMMAND_HELP,
    COMMAND_UNKNOWN,
    COMMAND_EMPTY;

}
